"""empty message

Revision ID: 0570d20a1fc7
Revises: f07972f1756d
Create Date: 2021-08-08 15:26:34.784124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0570d20a1fc7'
down_revision = 'f07972f1756d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('task_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'task', ['task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'task_id')
    # ### end Alembic commands ###
