"""empty message

Revision ID: 148364893030
Revises: fe32cf500ff9
Create Date: 2021-08-11 17:18:11.039556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '148364893030'
down_revision = 'fe32cf500ff9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('global_note', sa.Unicode(), nullable=True))
    op.add_column('task', sa.Column('global_position', sa.Integer(), nullable=True))
    op.drop_column('task', 'position')
    op.drop_column('task', 'note')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('note', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('task', 'global_position')
    op.drop_column('task', 'global_note')
    # ### end Alembic commands ###
