"""empty message

Revision ID: 2918fabf2155
Revises: 4d3948f52412
Create Date: 2021-08-08 16:00:12.357347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2918fabf2155'
down_revision = '4d3948f52412'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task_task_id_fkey', 'task', type_='foreignkey')
    op.drop_column('task', 'task_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('task_task_id_fkey', 'task', 'task', ['task_id'], ['id'])
    # ### end Alembic commands ###
