"""empty message

Revision ID: 3c5035172adc
Revises: c302055f99e9
Create Date: 2021-08-11 06:10:17.131152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c5035172adc'
down_revision = 'c302055f99e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('children', sa.Column('position', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'position')
    op.drop_column('children', 'position')
    # ### end Alembic commands ###
