"""empty message

Revision ID: 4d3948f52412
Revises: 0570d20a1fc7
Create Date: 2021-08-08 15:38:38.308524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d3948f52412'
down_revision = '0570d20a1fc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignments',
    sa.Column('task', sa.Integer(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task'], ['task.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], )
    )
    op.create_table('subtasks',
    sa.Column('parent', sa.Integer(), nullable=True),
    sa.Column('child', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['child'], ['task.id'], ),
    sa.ForeignKeyConstraint(['parent'], ['task.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subtasks')
    op.drop_table('assignments')
    # ### end Alembic commands ###
