"""empty message

Revision ID: 6173dcfe0e5e
Revises: 2918fabf2155
Create Date: 2021-08-09 17:00:19.595540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6173dcfe0e5e'
down_revision = '2918fabf2155'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('children',
    sa.Column('parent', sa.Integer(), nullable=True),
    sa.Column('child', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['child'], ['task.id'], ),
    sa.ForeignKeyConstraint(['parent'], ['task.id'], )
    )
    op.drop_table('subtasks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subtasks',
    sa.Column('parent', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('child', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['child'], ['task.id'], name='subtasks_child_fkey'),
    sa.ForeignKeyConstraint(['parent'], ['task.id'], name='subtasks_parent_fkey')
    )
    op.drop_table('children')
    # ### end Alembic commands ###
