"""empty message

Revision ID: c302055f99e9
Revises: 6173dcfe0e5e
Create Date: 2021-08-11 04:49:43.921613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c302055f99e9'
down_revision = '6173dcfe0e5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'score')
    # ### end Alembic commands ###
