"""empty message

Revision ID: f07972f1756d
Revises: 0a5440c224bf
Create Date: 2021-08-07 16:35:09.554633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f07972f1756d'
down_revision = '0a5440c224bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('name', sa.Unicode(), nullable=True))
    op.add_column('task', sa.Column('note', sa.Unicode(), nullable=True))
    op.drop_column('task', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('body', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('task', 'note')
    op.drop_column('task', 'name')
    # ### end Alembic commands ###
