"""empty message

Revision ID: f0f934a084df
Revises: 3c5035172adc
Create Date: 2021-08-11 09:53:09.866344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0f934a084df'
down_revision = '3c5035172adc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('children', sa.Column('note', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('children', 'note')
    # ### end Alembic commands ###
