"""empty message

Revision ID: fe32cf500ff9
Revises: f0f934a084df
Create Date: 2021-08-11 09:53:35.376256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe32cf500ff9'
down_revision = 'f0f934a084df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('children', sa.Column('check', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('children', 'check')
    # ### end Alembic commands ###
